// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV9_799wfD75Vf6RAWLY2Ac9JDkA2MnYQ',
    appId: '1:163765769261:web:ea3a1ff61fb0c7992294a4',
    messagingSenderId: '163765769261',
    projectId: 'shop-scouter',
    authDomain: 'shop-scouter.firebaseapp.com',
    storageBucket: 'shop-scouter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj6BqJGU_ipfK6f4nicbKR9h9DX7CgOk8',
    appId: '1:163765769261:android:8378fc86c8361df82294a4',
    messagingSenderId: '163765769261',
    projectId: 'shop-scouter',
    storageBucket: 'shop-scouter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Ot69MPZH968qtn6V5dGhSAawHUZDuEU',
    appId: '1:163765769261:ios:62052dd9e95db95a2294a4',
    messagingSenderId: '163765769261',
    projectId: 'shop-scouter',
    storageBucket: 'shop-scouter.firebasestorage.app',
    iosBundleId: 'com.shopscouter.shopScouter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Ot69MPZH968qtn6V5dGhSAawHUZDuEU',
    appId: '1:163765769261:ios:62052dd9e95db95a2294a4',
    messagingSenderId: '163765769261',
    projectId: 'shop-scouter',
    storageBucket: 'shop-scouter.firebasestorage.app',
    iosBundleId: 'com.shopscouter.shopScouter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV9_799wfD75Vf6RAWLY2Ac9JDkA2MnYQ',
    appId: '1:163765769261:web:ba07c416f0e09daf2294a4',
    messagingSenderId: '163765769261',
    projectId: 'shop-scouter',
    authDomain: 'shop-scouter.firebaseapp.com',
    storageBucket: 'shop-scouter.firebasestorage.app',
  );
}
